name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-openmrs-jfrog.yml@main
    secrets: inherit
