name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-versions:
    if: github.repository_owner == 'openmrs'
    permissions:
      contents: write
    concurrency:
      group: update-versions-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/update-versions.yml@main
    secrets: inherit

  build-and-publish:
    if: github.repository_owner == 'openmrs'
    needs: update-versions
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-openmrs-jfrog.yml@main
    secrets: inherit
